artifacts_root: olympics-all-in-all/artifacts

data_ingestion:
  root_dir: olympics-all-in-all/artifacts/data_ingestion
  source_data: olympics.zip
  local_data_file: olympics-all-in-all/artifacts/data_ingestion/olympics_data.zip
  unzip_dir: olympics-all-in-all/artifacts/data_ingestion

data_preprocesing:
  root_dir: olympics-all-in-all/artifacts/data_preprocess
  preprocessed_data_file_path: olympics-all-in-all/artifacts/data_preprocess/preprocessed_data.csv
