artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_data: olympics.zip
  local_data_file: artifacts/data_ingestion/olympics_data.zip
  unzip_dir: artifacts/data_ingestion
